# Generated by Django 6.0 on 2025-12-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_watchlistitem_unique_user_item"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="watchlistitem",
            name="unique_user_item",
        ),
        migrations.RenameField(
            model_name="watchlistitem",
            old_name="item",
            new_name="listing",
        ),
        migrations.AddConstraint(
            model_name="watchlistitem",
            constraint=models.UniqueConstraint(
                fields=("user", "listing"), name="unique_user_listing"
            ),
        ),
    ]
