# Generated by Django 6.0 on 2026-01-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_remove_watchlistitem_unique_user_item_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
