# Generated by Django 6.0 on 2025-12-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_watchlistitem"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="watchlistitem",
            constraint=models.UniqueConstraint(
                fields=("user", "item"), name="unique_user_item"
            ),
        ),
    ]
