# Generated by Django 6.0 on 2026-01-02 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_auctionlisting_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="commenter",
            new_name="user",
        ),
    ]
