# Generated by Django 6.0 on 2026-01-02 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_rename_commenter_comment_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
